import type { ChannelType, EvaluationParameter } from "@/types/quality";

export const WISE_CALL_PARAMETERS: EvaluationParameter[] = [
  // Sección A: Items (Gestión de la Llamada / Atención)
  {
    code: "call_cordialidad",
    name: "Cordialidad y cortesía",
    weight: 3,
    section: "items",
    channel: "wise_call",
    order: 1,
  },
  {
    code: "call_saludo_estandar",
    name: "Uso del saludo estándar",
    weight: 3,
    section: "items",
    channel: "wise_call",
    order: 2,
  },
  {
    code: "call_interes_resolver",
    name: "Demuestra interés en resolver el problema",
    weight: 3,
    section: "items",
    channel: "wise_call",
    order: 3,
  },
  {
    code: "call_sondeo",
    name: "Sondeo",
    weight: 6,
    section: "items",
    channel: "wise_call",
    order: 4,
  },
  {
    code: "call_escucha_activa",
    name: "Escucha en forma activa y atenta",
    weight: 6,
    section: "items",
    channel: "wise_call",
    order: 5,
  },
  {
    code: "call_control_conversacion",
    name: "Control de la conversación",
    weight: 3,
    section: "items",
    channel: "wise_call",
    order: 6,
  },
  {
    code: "call_contencion_espera",
    name: "Contención en la espera",
    weight: 3,
    section: "items",
    channel: "wise_call",
    order: 7,
  },
  {
    code: "call_despedida_cordial",
    name: "Se despide cordialmente",
    weight: 3,
    section: "items",
    channel: "wise_call",
    order: 8,
  },
  {
    code: "call_lenguaje_apropiado",
    name: "Lenguaje apropiado",
    weight: 5,
    section: "items",
    channel: "wise_call",
    order: 9,
  },
  {
    code: "call_procedimiento",
    name: "Cumplimiento de procedimiento",
    weight: 10,
    section: "items",
    channel: "wise_call",
    order: 10,
  },

  // Sección B: TICKET (Gestión y Registro en Sistema)
  {
    code: "call_ticket_origen",
    name: "Origen de la solicitud",
    weight: 6,
    section: "ticket",
    channel: "wise_call",
    order: 11,
  },
  {
    code: "call_ticket_tipo",
    name: "Tipo de solicitud",
    weight: 5,
    section: "ticket",
    channel: "wise_call",
    order: 12,
  },
  {
    code: "call_ticket_categorizacion",
    name: "Categorización",
    weight: 10,
    section: "ticket",
    channel: "wise_call",
    order: 13,
  },
  {
    code: "call_ticket_ortografia",
    name: "Ortografía",
    weight: 8,
    section: "ticket",
    channel: "wise_call",
    order: 14,
  },
  {
    code: "call_ticket_prioridad",
    name: "Prioridad",
    weight: 6,
    section: "ticket",
    channel: "wise_call",
    order: 15,
  },
  {
    code: "call_ticket_titulo",
    name: "Título",
    weight: 7,
    section: "ticket",
    channel: "wise_call",
    order: 16,
  },
  {
    code: "call_ticket_descripcion",
    name: "Descripción / Evidencia",
    weight: 7,
    section: "ticket",
    channel: "wise_call",
    order: 17,
  },
  {
    code: "call_ticket_exactitud_datos",
    name: "Exactitud en el ingreso de datos",
    weight: 6,
    section: "ticket",
    channel: "wise_call",
    order: 18,
  },
];

export const WISE_EMAIL_PARAMETERS: EvaluationParameter[] = [
  // Sección A: Items (Gestión general del correo)
  {
    code: "email_interpretacion",
    name: "Interpretación de la solicitud (A)",
    weight: 10,
    section: "items",
    channel: "wise_email",
    order: 1,
  },
  {
    code: "email_procedimientos",
    name: "Aplicación de procedimientos (B)",
    weight: 10,
    section: "items",
    channel: "wise_email",
    order: 2,
  },
  {
    code: "email_gestion_herramientas",
    name: "Gestión Outlook / Invgate (C)",
    weight: 10,
    section: "items",
    channel: "wise_email",
    order: 3,
  },
  {
    code: "email_redaccion",
    name: "Redacción y comunicación (D)",
    weight: 10,
    section: "items",
    channel: "wise_email",
    order: 4,
  },
  {
    code: "email_claridad",
    name: "Comunicación y claridad (E)",
    weight: 10,
    section: "items",
    channel: "wise_email",
    order: 5,
  },
  {
    code: "email_resolucion",
    name: "Resolución brindada (F)",
    weight: 10,
    section: "items",
    channel: "wise_email",
    order: 6,
  },
  {
    code: "email_seguimiento",
    name: "Seguimiento al cliente (G)",
    weight: 20,
    section: "items",
    channel: "wise_email",
    order: 7,
  },
  {
    code: "email_solicitud",
    name: "Solicitud",
    weight: null,
    section: "items",
    channel: "wise_email",
    order: 8,
  },
  {
    code: "email_sla_90min",
    name: "Responde dentro del tiempo establecido 90min",
    weight: 20,
    section: "items",
    channel: "wise_email",
    order: 9,
  },

  // Sección B: Items categoría MDA (Ticket derivado del correo)
  {
    code: "email_mda_sla_resolucion",
    name: "SLA de Resolución",
    weight: 10,
    section: "mda",
    channel: "wise_email",
    order: 10,
  },
  {
    code: "email_mda_seguimiento",
    name: "Seguimiento",
    weight: 10,
    section: "mda",
    channel: "wise_email",
    order: 11,
  },
  {
    code: "email_mda_categorizacion_final",
    name: "Categorización final",
    weight: 10,
    section: "mda",
    channel: "wise_email",
    order: 12,
  },
  {
    code: "email_mda_origen",
    name: "Origen de la solicitud",
    weight: 7,
    section: "mda",
    channel: "wise_email",
    order: 13,
  },
  {
    code: "email_mda_tipo",
    name: "Tipo de solicitud",
    weight: 5,
    section: "mda",
    channel: "wise_email",
    order: 14,
  },
  {
    code: "email_mda_categorizacion",
    name: "Categorización",
    weight: 10,
    section: "mda",
    channel: "wise_email",
    order: 15,
  },
  {
    code: "email_mda_ortografia",
    name: "Ortografía",
    weight: 10,
    section: "mda",
    channel: "wise_email",
    order: 16,
  },
  {
    code: "email_mda_prioridad",
    name: "Prioridad",
    weight: 10,
    section: "mda",
    channel: "wise_email",
    order: 17,
  },
  {
    code: "email_mda_titulo",
    name: "Título",
    weight: 8,
    section: "mda",
    channel: "wise_email",
    order: 18,
  },
  {
    code: "email_mda_descripcion",
    name: "Descripción / Evidencia",
    weight: 10,
    section: "mda",
    channel: "wise_email",
    order: 19,
  },
  {
    code: "email_mda_exactitud_datos",
    name: "Exactitud en el ingreso de datos",
    weight: 10,
    section: "mda",
    channel: "wise_email",
    order: 20,
  },
];

export const INVGATE_AG_PARAMETERS: EvaluationParameter[] = [
  // Sección A: Items (Gestión general del caso)
  {
    code: "ag_titulo",
    name: "Corrección del título de la solicitud (A)",
    weight: 10,
    section: "items",
    channel: "invgate_ticket",
    order: 1,
  },
  {
    code: "ag_analisis",
    name: "Análisis de la solicitud (B)",
    weight: 10,
    section: "items",
    channel: "invgate_ticket",
    order: 2,
  },
  {
    code: "ag_sondeo",
    name: "Sondeo, pruebas realizadas (C)",
    weight: 10,
    section: "items",
    channel: "invgate_ticket",
    order: 3,
  },
  {
    code: "ag_procedimiento",
    name: "Cumplimiento del procedimiento (D)",
    weight: 20,
    section: "items",
    channel: "invgate_ticket",
    order: 4,
  },
  {
    code: "ag_documentacion",
    name: "Documentación de la gestión (E)",
    weight: 10,
    section: "items",
    channel: "invgate_ticket",
    order: 5,
  },
  {
    code: "ag_correccion_prioridad",
    name: "Corrección de prioridad",
    weight: 10,
    section: "items",
    channel: "invgate_ticket",
    order: 6,
  },
  {
    code: "ag_correccion_tipo",
    name: "Corrección de Tipo de solicitud",
    weight: 10,
    section: "items",
    channel: "invgate_ticket",
    order: 7,
  },
  {
    code: "ag_categorizacion",
    name: "Categorización (F)",
    weight: 20,
    section: "items",
    channel: "invgate_ticket",
    order: 8,
  },

  // Sección B: Items categoría MDA
  {
    code: "ag_mda_sla_primera_respuesta",
    name: "SLA de Primera respuesta",
    weight: 20,
    section: "mda",
    channel: "invgate_ticket",
    order: 9,
  },
  {
    code: "ag_mda_sla_resolucion",
    name: "SLA de Resolución",
    weight: 20,
    section: "mda",
    channel: "invgate_ticket",
    order: 10,
  },
  {
    code: "ag_mda_seguimiento",
    name: "Seguimiento",
    weight: 20,
    section: "mda",
    channel: "invgate_ticket",
    order: 11,
  },
  {
    code: "ag_mda_categorizacion_final",
    name: "Categorización final",
    weight: 20,
    section: "mda",
    channel: "invgate_ticket",
    order: 12,
  },
  {
    code: "ag_mda_info_complementaria",
    name: "Información complementaria",
    weight: 10,
    section: "mda",
    channel: "invgate_ticket",
    order: 13,
  },
  {
    code: "ag_mda_ortografia",
    name: "Ortografía",
    weight: 10,
    section: "mda",
    channel: "invgate_ticket",
    order: 14,
  },
];

export function getChannelParameters(channel: ChannelType): EvaluationParameter[] {
  switch (channel) {
    case "wise_call":
      return WISE_CALL_PARAMETERS;
    case "wise_email":
      return WISE_EMAIL_PARAMETERS;
    case "invgate_ticket":
      return INVGATE_AG_PARAMETERS;
    default:
      return [];
  }
}
